import { runActivitySummaryMoveTests } from '../activity/testActivitySummaryMoves';
import { runActivitySummarySelectorTests } from '../activity/testActivitySummarySelector';
import { runActivitySummaryBalancedTests } from '../activity/testActivitySummaryBalanced';
import { runActivitySessionTests } from '../activity/testActivitySession';
import { runActivitySummaryAtTests } from '../activity/testActivitySummaryAt';
import { runActivityTwoAgentsTests } from '../activity/testActivityTwoAgents';
import { runActivitySummaryPresenterTests } from '../activity/testActivitySummaryPresenter';
import { runActivitySummaryFormatterTests } from '../activity/testActivitySummaryFormatter';
import { runActivitySummaryTests } from '../activity/testActivitySummary';
import { runActivitySummaryScenarioTests } from '../activity/testActivitySummaryScenarios';
import { runTwoPhaseTickTests } from './testTwoPhaseTick';
import { runSocialSelectionTests } from './testSocialSelection';
import { runSocialEventCharacterizationTests } from './testSocialEventCharacterization';
import { runWorkScheduleTests } from './testWorkSchedule';
import { runIsolatedPersonalityTests } from './testPersonalitySocial';
import { runIsolatedSleepTests } from './testSleepCycle';
import { runIsolatedBiologicalTests } from './testBiologicalBalance';
import { runIntegrityTests } from './testIntegrity';

runIsolatedPersonalityTests();
runIsolatedSleepTests();
runIsolatedBiologicalTests();
runIntegrityTests();
runWorkScheduleTests();
runSocialSelectionTests();
runTwoPhaseTickTests();
runActivitySummaryTests();
runActivitySummaryFormatterTests();
runActivitySummaryMoveTests();
runActivitySummarySelectorTests();
runActivitySummaryBalancedTests();
runActivitySummaryPresenterTests();
runActivitySummaryScenarioTests();
runActivitySessionTests();
runActivitySummaryAtTests();
runActivityTwoAgentsTests();
runSocialEventCharacterizationTests();
console.log('All tests passed.');
